### ISSUE TITLE
关于new Watch(this)的问题

### ISSUE THREAD

**Issue by lance-yi** [jayZOU/watch#3]
请问一下，这个是直接把watch.js文件copy下来放在项目中，在页面中import进来，实例化是哪里进行的？

**Comment by jayZOU** [comment]
直接把watch.js文件copy下来放在项目中
在页面中引入，在生命周期内实例化就可以了

**Comment by lance-yi** [comment]
![image](https://user-images.githubusercontent.com/33007678/40463413-d39068b6-5f47-11e8-8eda-ca57f8ff2ebe.png)
好像没有起作用呢~

**Comment by lance-yi** [comment]
![image](https://user-images.githubusercontent.com/33007678/40463586-a656f3d2-5f48-11e8-87ce-42cca3644fe9.png)
抱歉，大神，我没有注意到，这里要把监听的数据放进去是吧？

**Comment by jayZOU** [comment]
watch.setData 会调用原生的setData并且执行你在watch注入的回调

**Comment by Akiq2016** [comment]
@jayZOU 你好 想问一下 `setter` 方法里的 `depDataNote` 意义是什么

**Comment by dave-wind** [comment]
```js
'b.c.d': function (val, oldVal) {
      console.log('new: %s, old: %s', val, oldVal);
}
```
* 第一个参数是oldVal 第二个才是 val 吧

**Comment by jayZOU** [comment]
> 你好 想问一下 setter 方法里的 depDataNote 意义是什么

@Akiq2016 当时是想着保存每次reduce遍历路径之后的结果，当时有点迷糊了，没想到result就是结果了

**Comment by jayZOU** [comment]
@dave-wind 第一个参数是val（新值） 第二个才是 oldVal（旧值） 吧

**Comment by jayZOU** [comment]
大家有问题可以新开issue，这个我先关了
