### ISSUE TITLE
不错！

### ISSUE THREAD

**Issue by xixilive** [jayZOU/watch#5]
若是进一步抽象成middleware机制是否会给developer更广的使用场景？

比如：

```js
this.use((preVal, nextVal) => {
  console.log(`oldValue: ${preVal}, newValue: ${nextVal}`)
  return Object.assign(nextState, {adding: 'more'}) // setData with new value after all middlewares
})
```

如何从release version中移除这些用于debug场景的代码？

**Comment by jayZOU** [comment]
设计的时候也是有考虑过抽象成middleware机制，不过当初并不打算把这个库做的那么重，后续如果有这方面需求的话也可以考虑引入middleware了。

> 如何从release version中移除这些用于debug场景的代码？  

你说的debug场景的代码是指哪一块呢？
