### ISSUE TITLE
watch.setData 监听不到多层数据的oldVal

### ISSUE THREAD

**Issue by blogwy** [jayZOU/watch#6]
--当前的表现
        a: function(val, oldVal) {
            console.log('new: %s, old: %s', val, oldVal);
        },
        'b.c.d': function(val, oldVal) {
            console.log('new: %s, old: %s', val, oldVal);
        }
写了一个按钮，用watch.setData来改变a 和 b.c.d的值，发现可以监听到a的当前值和以前的值，b.c.d监听到两个值都是当前值。

**Comment by jayZOU** [comment]
已解决，这里我忽略了Object.assign无法深克隆嵌套数据的问题，改用`JSON.parse(JSON.stringify(this.page.data))`方式来解决，虽然针对function和undefined类型无法copy，但是因为小程序的data使用的原因，使用JSON做深克隆就可以的
![image](https://user-images.githubusercontent.com/8576977/47426842-06f24200-d7c1-11e8-81df-21337e110b40.png)
